---
- name: handling user {{ user.key }}
  ansible.builtin.user:
    append: "{{ user.value.append | default(omit) }}"
    authorization: "{{ user.value.authorization | default(omit, true) }}"
    comment: "{{ user.value.comment |default(omit) }}"
    create_home: "{{ user.value.create_home | default('true', true) }}"
    expires: "{{ user.value.expires | default(omit) }}"
    force: "{{ user.value.force | default('false', true) }}"
    generate_ssh_key: "{{ user.value.generate_ssh_key | default('false', true) }}"
    group: "{{ user.value.group | default(omit, true) }}"
    groups: "{{ user.value['groups_byhostname'][inventory_hostname] | default(omit) }}"
    home: "{{ user.value.home | default(omit, true) }}"
    local: "{{ user.value.local | default(omit, true) }}"
    login_class: "{{ user.value.login_class | default(omit) }}"
    move_home: "{{ user.value.move_home | default('false') }}"
    name: "{{ user.key }}"
    non_unique: "{{ user.value.non_unique | default('false') }}"
    password: "{{ user.value.password | default(omit) }}"
    password_expire_max: "{{ user.value.password_expire_max | default(omit) }}"
    password_expire_min: "{{ user.value.password_expire_min | default(omit) }}"
    password_lock: "{{ user.value.password_lock | default(omit) }}"
    remove: "{{ user.value.remove | default('false') }}"
    role: "{{ user.value.role | default(omit) }}"
    seuser: "{{ user.value.seuser | default(omit) }}"
    shell: "{{ usershell | default(omit) }}"
    skeleton: "{{ user.value.skeleton | default(omit) }}"
    ssh_key_bits: "{{ user.value.ssh_key_bits | default(omit) }}"
    ssh_key_comment: "{{ user.value.ssh_key_comment | default(omit) }}"
    ssh_key_file: "{{ user.value.ssh_key_file | default(omit) }}"
    ssh_key_passphrase: "{{ user.value.ssh_key_passphrase | default(omit) }}"
    ssh_key_type: "{{ user.value.ssh_key_type | default(omit) }}"
    state: "{{ user.value.state | default('present', true) }}"
    system: "{{ user.value.system | default('false') }}"
    uid: "{{ user.value.uid | default(omit) }}"
    umask: "{{ user.value.umask | default(omit) }}"
    update_password: "{{ user.value.update_password | default('always') }}"
