- name: Setup MOTD Linux
  ansible.builtin.template:
    src: motd
    dest: /etc/motd
    owner: root
    group: root
    mode: 0644
  when: (ansible_facts['os_family'] == "RedHat") or (ansible_facts['os_family'] == "Alpine") or (ansible_facts['os_family'] == 'Debian') or (ansible_os_family == 'Archlinux')
- name: FreeBSD 12 setup MOtD
  ansible.builtin.template:
    src: motd
    dest: /etc/motd
    owner: root
    group: wheel
    mode: 0644
  when:
    - ansible_facts['os_family'] == "FreeBSD"
    - ansible_distribution_major_version == "12"
- name: FreeBSD 13 setup MOtD
  ansible.builtin.template:
    src: motd
    dest: /etc/motd.template
    owner: root
    group: wheel
    mode: 0644
  when:
    - ansible_os_family == "FreeBSD"
    - ansible_distribution_major_version == "13"
  notify: restart motd
- name: FreeBSD 13 set update_motd
  ansible.builtin.template:
    src: rc.conf.jinja2
    dest: /etc/rc.conf.d/motd
    owner: root
    group: wheel
    mode: 0644
  when:
    - ansible_os_family == "FreeBSD"
    - ansible_distribution_major_version == "13"
