---
# tasks file for ansible_podman
- name: Setting OS variables
  ansible.builtin.include_vars: "{{lookup('ansible.builtin.first_found', params)}}"
  vars:
    params:
      files:
        - "{{ ansible_distribution }}.yml"
        - "{{ ansible_os_family }}.yml"
        - "default.yml"
      paths:
        - "vars"
# Installations
- name: Set package name for calling packages role
  ansible.builtin.set_fact:
    packages_installrole: "{{ podman_packages }}"
- name: install required packages
  ansible.builtin.include_role:
    name: imp1sh.ansible_managemynetwork.ansible_packages
  when: ansible_distribution != "OpenWrt"
- name: install packages OpenWrt
  community.general.opkg:
    name: "{{ packages_installrole }}"
    state: present
  when: ansible_distribution == "OpenWrt"
- name: Create networks
  containers.podman.podman_network:
    name: "{{ item.name }}"
    driver: "{{ item.driver }}"
    ipv6: "{{ item.ipv6 }}"
  loop: "{{ podman_networks }}"
- name: ensure podman container directories
  ansible.builtin.file:
    path: "{{ item.1 | split(':') | first | ansible.builtin.dirname }}"
    state: directory
  loop: "{{ podman_containers | subelements('volume', 'skip_missing=True') }}"
- name: Create containers
  containers.podman.podman_containers:
    containers: "{{ podman_containers }}"
- name: systemd tasks
  ansible.builtin.include_tasks:
    file: systemd.yml
  when: ansible_distribution != "OpenWrt"
  loop: "{{ podman_containers }}"
  loop_control:
    loop_var: podman_container
- name: procd tasks
  ansible.builtin.include_tasks:
    file: procd.yml
  when: ansible_distribution == "OpenWrt"
  loop: "{{ podman_containers }}"
  loop_control:
    loop_var: podman_container
