# code: language=ansible
---
- block:
  - name: What user am I currently working on
    ansible.builtin.debug:
      var: user.key
  - name: Clone oh-my-zsh for users
    tags:
      # Suppress warning: [ANSIBLE0006] git used in place of git module
      # Git module doesn't allow us to set `core.autocrlf=input`.
      - skip_ansible_lint
    become: true
    become_user: '{{ user.key }}'
    # core.autocrlf=input prevents https://github.com/ohmyzsh/ohmyzsh/issues/4402
    ansible.builtin.command: 'git clone -c core.autocrlf=input --depth=1 https://github.com/ohmyzsh/ohmyzsh.git .oh-my-zsh'
    args:
      chdir: '~{{ user.key }}'
      creates: '~{{ user.key }}/.oh-my-zsh'
  - name: Set permissions of oh-my-zsh for users
    become: true
    ansible.builtin.file:
      path: '~{{ user.key }}/.oh-my-zsh'
      # Prevent the cloned repository from having insecure permissions. Failing to do
      # so causes compinit() calls to fail with "command not found: compdef" errors
      # for users with insecure umasks (e.g., "002", allowing group writability).
      mode: 'go-w'
      recurse: true
  - name: Set default shell for users
    become: true
    ansible.builtin.user:
      name: '{{ user.key }}'
      shell: '{{ oh_my_zsh_zsh_path }}'
    when: user.value.shell == "zsh"
  - name: Install oh-my-zsh auto suggestions
    ansible.builtin.git:
      repo: 'https://github.com/zsh-users/zsh-autosuggestions'
      dest: "~{{ user.key }}/.oh-my-zsh/plugins/zsh-autosuggestions"
    become: true
    become_user: '{{ user.key }}'
    when: '"zsh-autosuggestions" in user.value.oh_my_zsh.plugins'
  - name: Write .zshrc for users
    ansible.builtin.template:
      src: zshrc.j2
      owner: "{{ user.key }}"
      dest: '~{{ user.key }}/.zshrc'
      backup: true
      mode: 'u=rw,go=r'
    when: >-
      ((user.value.oh_my_zsh.install | default(oh_my_zsh_install)) | bool)
      and ((user.value.oh_my_zsh.write_zshrc | default(oh_my_zsh_write_zshrc)) | bool)
  - name: Set environment variables
    ansible.builtin.template:
      src: "ENVS.j2"
      dest: "~{{ user.key }}/.oh-my-zsh/custom/envs.zsh"
      owner: "{{ user.key }}"
      mode: "go-w"
    when: user.value.envs is defined
  - name: Install zsh customizations
    ansible.builtin.copy:
      src: "{{ custom_item }}"
      dest: "~{{ user.key }}/.oh-my-zsh/custom/{{ custom_item }}.zsh"
      owner: "{{ user.key }}"
      mode: "go-w"
    loop: "{{ user.value.oh_my_zsh.customs }}"
    loop_control:
      loop_var: custom_item
    when: user.value.oh_my_zsh.customs is defined
  when:
    - user.value.oh_my_zsh is defined
    - "((user.value.oh_my_zsh | default({})).install | default(oh_my_zsh_install)) | bool"


