# code: language=ansible
---
- name: Setting OS variables
  ansible.builtin.include_vars: "{{ lookup('ansible.builtin.first_found', params) }}"
  vars:
    params:
      files:
        - '{{ ansible_facts.os_family }}.yml'
        - default.yml
      paths:
        - vars

- name: Set package name for calling packages role
  ansible.builtin.set_fact:
    packages_installrole: "{{ oh_my_zsh_dependencies }}"
- name: install required packages
  ansible.builtin.include_role:
    name: imp1sh.ansible_managemynetwork.ansible_packages

- name: Install Oh My Zsh
  ansible.builtin.include_tasks: install.yml
  loop: "{{ system_users | dict2items }}"
  loop_control:
    loop_var: user

- name: Console setup for Debian family distributions
  ansible.builtin.include_tasks: debian-console-setup.yml
  when: ansible_facts.os_family == 'Debian'
