---
# defaults file for ansible_borgmatic
borgmatic_packageapprisepip: "apprise"
borgmatic_venv_wrapper: "/usr/local/sbin/borgmatic_venv"
borgmatic_path_apprise_script: "/usr/local/bin"
borgmatic_apprise_via_pip: true
borgmatic_via_pip: true
borgmatic_venvdir: "/opt/venv/borgmatic"
borgmatic_cron_name: borgmatic
borgmatic_cron_hourrange_start: 1
borgmatic_cron_hourrange_end: 6
borgmatic_cron_minuterange_start: 1
borgmatic_cron_minuterange_end: 59
borgmatic_cron_hour: "{{ borgmatic_cron_hourrange_end | random(start=borgmatic_cron_hourrange_start, seed=inventory_hostname) }}"
borgmatic_cron_minute: "{{ borgmatic_cron_minuterange_end | random(start=borgmatic_cron_minuterange_start, seed=inventory_hostname) }}"
borgmatic_cron_manage: True
borgmatic_ssh_manage: True
