---
# tasks file for ansible_nginx
- name: include OS vars
  ansible.builtin.include_vars: "{{ ansible_distribution }}.yml"
- name: Install components
  ansible.builtin.include_tasks: install.yml
- name: Preparations
  ansible.builtin.include_tasks: prepare.yml
- name: Configurations
  ansible.builtin.include_tasks: configure.yml
- name: Setup nginx vhost items task
  ansible.builtin.include_tasks: vhosts.yml
  loop: "{{ nginx_vhosts }}"
  loop_control:
    loop_var: vhostitem
  when: nginx_vhosts is defined
- name: Setup nginx rproxy items task
  ansible.builtin.include_tasks: rproxy-vhosts.yml
  loop: "{{ nginx_rproxyitems }}"
  loop_control:
    loop_var: rproxyitem
  when: nginx_rproxyitems is defined
- name: enable nginx
  ansible.builtin.service:
    name: "{{ nginx_servicename }}"
    enabled: yes
    state: started

