---
- name: create vhost root dir
  ansible.builtin.file:
    path: "{{ nginx_wwwdir }}/vhosts/{{ vhostitem.fqdn }}"
    state: directory
    mode: '0750'
    owner: "{{ nginx_user }}"
    group: "{{ nginx_group }}"
- name: "Install nginx vhost item {{ vhostitem.fqdn }}"
  ansible.builtin.template:
    src: vhost_http.conf.j2
    dest: "{{ nginx_confdir }}/http.d/{{ vhostitem.fqdn }}.conf"
    owner: "{{ nginx_confowner }}"
    group: "{{ nginx_confgroup }}"
    mode: '0744'
  notify:
    - reload nginx
- name: "Use manually defined cert"
  ansible.builtin.set_fact:
    vhost_certname: "{{ vhostitem.usecert }}"
  when: vhostitem.usecert is defined
- name: "Use vhost main name as certname"
  ansible.builtin.set_fact:
    vhost_certname: "{{ vhostitem.fqdn }}"
  when: vhostitem.usecert is not defined
- name: "Check if vhost item has fullchain.pem"
  ansible.builtin.stat:
    path: "{{ nginx_certpath }}/{{ vhost_certname }}/fullchain.pem"
  register: vhostitem_fullchain
- name: "Check if vhost item has privkey.pem"
  ansible.builtin.stat:
    path: "{{ nginx_certpath }}/{{ vhost_certname }}/privkey.pem"
  register: vhostitem_privkey
- name: "Installing nginx vhost https item {{ vhostitem.fqdn }} if certs are available"
  ansible.builtin.template:
    src: vhost_https.conf.j2
    dest: "{{ nginx_confdir }}/http.d/{{ vhostitem.fqdn }}-tls.conf"
    owner: "{{ nginx_confowner }}"
    group: "{{ nginx_confgroup }}"
  when:
    - vhostitem_fullchain.stat.exists
    - vhostitem_privkey.stat.exists
  notify:
    - reload nginx
