---
- name: 0) /etc/hosts 파일 배포
  hosts: all
  gather_facts: false  # 매직변수는 fact 변수가 아님
  tasks:
    - name: 1) 관리 호스트에 /etc/hosts 파일 배포
      ansible.builtin.template:
        src: templates/hosts.j2
        dest: /root/hosts
        owner: root
        group: root
        mode: '0644'
