- name: Include Debian dependant
  import_tasks: debian.yml
  when: ansible_distribution == 'Debian'
- name: Include Alpine dependant
  import_tasks: alpine.yml
  when: ansible_os_family == 'Alpine'
- name: Include FreeBSD dependant
  import_tasks: freebsd.yml
  when: ansible_os_family == 'FreeBSD'

