---
######################################################
# 1. Play1: 파일 서버 설정
# * 1) 변수 포함
# * 2) 원격 디렉토리 생성
# * 3) 디버깅 메세지
######################################################
- name: 1. Play1 - 파일 서버 설정
  hosts: fileservers
  tasks:
    - name: 1) 변수 포함
      ansible.builtin.include_vars: paths.yml

    - name: 2) 원격 디렉토리 생성 - {{ paths.fileserver }} 생성
      ansible.builtin.file:
        path: "{{ paths.fileserver }}"
        mode: '0755'
        state: directory
      register: output

    - name: 3) 디버깅 메세지
      ansible.builtin.debug:
        var: output.path