---
galaxy_info:
  role_name: ansible_sudo
  author: Jochen Demmer
  description: Installs sudo and configures sudoers.d
  company: libcom.de
  issue_tracker_url: https://github.com/imp1sh/ansible_managemynetwork/issues
  license: BSD-3-Clause
  min_ansible_version: "2.9"
  platforms:
    - name: Debian
      versions:
        - all
    - name: Ubuntu
      versions:
        - all
  galaxy_tags: [system, sudo, sudoers]
dependencies: []
