---
- name: 하드웨어 보고서 작성
  hosts: all
  gather_facts: true
  tasks:
  ####################################################################
  # 1) 파일 배포 - files/hwreport.txt --배포--> /root/hwreport.txt
  # 2) 파일 편집
  # * inventoryhostname
  # * totalmem
  # * biosversion
  # * sdasize
  # 3) 파일 수집
  ####################################################################
  - name: 1) 파일 배포 - files/hwreport.txt --배포--> /root/hwreport.txt
    ansible.builtin.copy:
      src: files/hwreport.txt
      dest: /root/hwreport.txt
      owner: root
      group: root
      mode: '0644'

  - name: 2) 파일 편집 - (replace) inventoryhostname
    ansible.builtin.replace:
      path: /root/hwreport.txt
      regexp: inventoryhostname
      # 정규 표현식에 해당하는 문자를
      replace: "{{ inventory_hostname }}"
      # 해당 문자로 변경한다

  - name: 2) 파일 편집 - (replace) totalmem
    ansible.builtin.replace:
      path: /root/hwreport.txt
      regexp: totalmem
      replace: "{{ ansible_memtotal_mb }}"
      
  - name: 2) 파일 편집 - (replace) biosversion
    ansible.builtin.replace:
      path: /root/hwreport.txt
      regexp: biosversion
      replace: "{{ ansible_bios_version }}"

  - name: 2) 파일 편집 - (replace) sdasize
    ansible.builtin.lineinfile:
      path: /root/hwreport.txt
      regexp: sdasize
      line: "{{ ansible_devices.sda.size }}"

  - name: 3) 파일 수집 - (fetch)
    ansible.builtin.fetch:
      src: /root/hwreport.txt
      dest: results/{{ inventory_hostname }}-hwreport.txt
      flat: true

      # 아래와 같은 결과
      #dest: results/
      #flat: false\