- name: Install FreeBSD packages
  pkgng:
          name: "mono libass fontconfig freetype2 fribidi gnutls iconv opus samba411 sqlite3 libtheora libva libvpx libvorbis webp libx264 x265 dav1d libzvbi libraw ImageMagick6"
          state: present
- name: Install Emby Server
  command: pkg add -f https://github.com/MediaBrowser/Emby.Releases/releases/download/4.6.0.35/emby-server-freebsd12_4.6.0.35_amd64.txz
- name: Enable Emby Service
  service:
    name: emby-server
    enabled: yes
    state: started
  ignore_errors: yes
