---
galaxy_info:
  role_name: ansible_netbox2yaml
  author: Jochen Demmer
  description: Fetches multiple facts from netbox and makes them available in Ansible
  company: libcom.de
  issue_tracker_url: https://github.com/imp1sh/ansible_managemynetwork/issues
  license: BSD-3-Clause
  min_ansible_version: "2.9"
  platforms:
    - name: Debian
      versions:
        - "bookworm"
        - "bullseye"
  galaxy_tags: [netbox, netbox2yaml, netbox2yml, facts]
dependencies: []
