---
# Pretasks
- name: Checking the following key
  ansible.builtin.debug:
    var: sshkey.key
- name: Set system_sshkeys_isingroup and system_sshkeys_isinlist initially to False
  ansible.builtin.set_fact:
    system_sshkeys_isingroup: False
    system_sshkeys_isinlist: False

# Check for group based assignments
- name: check if subelement exists
  ansible.builtin.set_fact:
    system_sshkeys_elementcheck_group: "{{ system_sshkeys_deploy_on_hostgroups[sshkey.key] is defined }}"

- name: check if key is in group
  ansible.builtin.set_fact:
    system_sshkeys_isingroup: True
  when:
    - system_sshkeys_elementcheck_group
    - system_sshkeys_deploy_on_hostgroups[sshkey.key]['hostgroups'] | intersect(group_names) | length > 0

- name: Get destination username from group assignment
  ansible.builtin.set_fact:
    system_sshkeys_destinationusers: "{{ system_sshkeys_deploy_on_hostgroups[sshkey.key]['users'] }}"
  when: system_sshkeys_isingroup

# Check for individual host assigments
- name: individual check only necessary when not found in group
  block:
    - name: check if subelement exists in individual list
      ansible.builtin.set_fact:
        system_sshkeys_elementcheck_individual: "{{ system_sshkeys_deploy_on_hosts[sshkey.key] is defined }}"
    
    - name: Check if key is in hostlist
      ansible.builtin.set_fact:
        system_sshkeys_isinlist: "{{ inventory_hostname in system_sshkeys_deploy_on_hosts[sshkey.key] }}"
      when: system_sshkeys_elementcheck_individual
    
    - name: Get destination username from individual assignment
      ansible.builtin.set_fact:
        system_sshkeys_destinationusers: "{{ system_sshkeys_deploy_on_hosts[sshkey.key]['users'] }}"
      when: system_sshkeys_isinlist
  when: not system_sshkeys_isingroup

- name: Block task if key shall be deployed on this very host
  block:
    - name: The key will be handled
      ansible.builtin.debug:
        var: sshkey.key
    - name: Deploy key
      ansible.builtin.include_tasks: justdoit.yml
      loop: "{{ system_sshkeys_destinationusers }}"
      loop_control:
        loop_var: destinationuser
  when: (system_sshkeys_isinlist) or (system_sshkeys_isingroup)
