---
- name: Setting OS variables 
  ansible.builtin.include_vars: "{{lookup('ansible.builtin.first_found', params)}}"
  vars:
    params:
      files:
        - "{{ ansible_distribution }}.yml"
        - "{{ ansible_os_family }}.yml"
        - "default.yml"
      paths:
        - "vars"
- import_tasks: commonlinux.yml
  when: ansible_facts['os_family'] == 'Alpine'
- import_tasks: commonlinux.yml
  when: ansible_facts['os_family'] == 'RedHat'
- import_tasks: commonlinux.yml
  when: ansible_facts['os_family'] == 'FreeBSD'
- import_tasks: commonlinux.yml
  when: ansible_facts['os_family'] == 'Debian'
- import_tasks: commonlinux.yml
  when: ansible_facts['os_family'] == 'FreeBSD'
- import_tasks: commonlinux.yml
  when: ansible_facts['os_family'] == 'Archlinux'
    #- import_tasks: openwrt.yml
    #  when: ansible_facts['os_family'] == 'OpenWrt'
