galaxy_info:
  role_name: motd
  author: imp1sh
  description: Sets the message of the day for login screen.
  license: license (BSD, MIT)
  min_ansible_version: 2.0
  platforms:
  - name: Alpine
    versions:
      - all
  - name: FreeBSD
    versions:
      - all
  - name: EL
    versions:
      - 5
      - 6
      - 7
      - 8
  - name: Debian
    versions:
      - all

  galaxy_tags:
  - motd
  - login

dependencies: []
