---
- name: include OS vars
  include_vars: "{{ ansible_distribution }}.yml"
- name: Set package name for calling packages role
  ansible.builtin.set_fact:
    packages_installrole: "{{ chronyd_packagename }}"
- name: install required packages
  ansible.builtin.include_role:
    name: imp1sh.ansible_managemynetwork.ansible_packages
- name: setup conf.d dir for non ansible config options
  file:
    path: "{{ chronyd_pathconfig }}/{{ chronyd_config_includedir }}"
    state: directory
    owner: "{{ chronyd_fileowner }}"
    group: "{{ chronyd_filegroup }}"
    mode: 0755
  when: chronyd_config_includedir is defined
- name: Implant chrony configuration file
  ansible.builtin.template:
    src: "{{ chronyd_filetemplate }}"
    dest: "{{ chronyd_pathconfig }}/{{ chronyd_fileconfig }}"
  notify: restart chronyd
- name: Disable systemd-timesyncd
  ansible.builtin.service:
    name: systemd-timesyncd
    state: stopped
    enabled: no
  when: ansible_service_mgr == "systemd"
  ignore_errors: true
- name: Enable chrony service
  ansible.builtin.service:
    name: "{{ chronyd_servicename }}"
    state: started
    enabled: true
  ignore_errors: yes
