galaxy_info:
  role_name: systemdns
  author: imp1sh
  description: configures system DNS meaning resolv.conf
  license: license (BSD, MIT)
  min_ansible_version: 2.0
  platforms:
  - name: Alpine
    versions:
    - all

  galaxy_tags:
  - dns
  - resolvconf

dependencies: []
