---
galaxy_info:
  role_name: ansible_chrony
  author: Jochen Demmer
  description: Configures Chrony as server or client
  company: libcom.de
  issue_tracker_url: https://github.com/imp1sh/ansible_managemynetwork/issues
  license: BSD-3-Clause
  min_ansible_version: "2.9"
  platforms:
    - name: Debian
      versions:
        - "bookworm"
        - "bullseye"
  galaxy_tags: [chrony, ntp, sync]
dependencies: []
