---
# tasks file for ansible_wikijs
- name: include OS vars
  include_vars: "{{ ansible_distribution }}.yml"
- name: "Install requiremed packages"
  ansible.builtin.package:
    name: "{{ wikijs_packages }}"
    state: present
- name: "create wikijs directories"
  ansible.builtin.file:
    path: "{{ item['path'] }}"
    state: directory
    owner: "{{ item['runasuser'] }}"
    group: "{{ item['runasgroup'] }}"
  with_items:
    - "{{ wikijsinstances }}"
- name: "create logging directories"
  ansible.builtin.file:
    path: "/var/log/{{ item['name'] }}"
    state: directory
    owner: "{{ item['runasuser'] }}"
    group: "{{ item['runasgroup'] }}"
  with_items:
    - "{{ wikijsinstances }}"
- name: "fetch and extract wikijs instances"
  ansible.builtin.unarchive:
    src: "{{ item['url'] }}"
    dest: "{{ item['path'] }}"
    owner: "{{ item['runasuser'] }}"
    group: "{{ item['runasgroup'] }}"
    remote_src: yes
  with_items:
    - "{{ wikijsinstances }}"
  notify: "{{ wikijs_restartservice }}"
- name: "setup wikijs config"
  ansible.builtin.template:
    src: config.yml.j2
    dest: "{{ item['path'] }}/config.yml"
    owner: "{{ item['runasuser'] }}"
    group: "{{ item['runasgroup'] }}"
  with_items:
    - "{{ wikijsinstances }}"
  notify: "{{ wikijs_restartservice }}"
- name: Install npm for FreeBSD
  ansible.builtin.package:
    name: npm
    state: present
  when: ansible_facts['os_family'] == 'FreeBSD'
- name: Install pm2 via npm on FreeBSD
  npm:
    name: pm2
    global: yes
    state: present
  when: ansible_facts['os_family'] == 'FreeBSD'
- name: "setup openrc script for Alpine systems"
  ansible.builtin.template:
    src: openrc.j2
    dest: "/etc/init.d/{{ item['name'] }}"
    mode: 0770
  with_items:
    - "{{ wikijsinstances }}"
  when: ansible_facts['os_family'] == 'Alpine'
- name: "Setup systemd service"
  template:
    src: "systemd.jinja2"
    dest: "/etc/systemd/system/{{ item.name }}.service"
    owner: root
    group: root
  loop: "{{ wikijsinstances }}"
  when:
    - ansible_distribution == "Debian"
- name: "systemd reload"
  command: systemctl daemon-reload
  when:
    - ansible_distribution == "Debian"
- name: "systemd enable"
  service:
    name: "{{ item['name'] }}"
    state: started
    enabled: true
  loop: "{{ wikijsinstances }}"
  when:
    - ansible_distribution == "Debian"
- name: "Enable and start service"
  ansible.builtin.service:
    name: "{{ item['name'] }}"
    state: started
    enabled: true
  when: ansible_facts['os_family'] == 'Alpine'
  with_items:
    - "{{ wikijsinstances }}"
