- name: Set timezone Europe/Berlin
  community.general.timezone:
    name: Europe/Berlin
  when: ansible_facts['os_family'] != 'Alpine'
- name: Alpine specific
  ansible.builtin.command: setup-timezone -z {{ timezone }}
  when: ansible_facts['os_family'] == 'Alpine'
