---
- name: Restore playbook.yml
  hosts: all
  vars:
    packages:
      - mariadb
      - mariadb-server
      - python3-PyMySQL
    service: mariadb
  tasks:
  ###################################################################
  # 1) 패키지 설치 - mariadb, mariadb-server, python3-PyMySQL
  # 2) 서비스 기동 - mariadb.service
  ###################################################################
  - name: 2) 서비스 종료
    ansible.builtin.systemd:
      name: "{{ service }}"
      state: stopped
      enabled: false
    ignore_errors: true

  - name: 1) 패키지 삭제
    ansible.builtin.yum:
      name: "{{ packages }}"
      state: absent
    when: ansible_distribution == 'CentOS'

  