---
- name: List of packages to be removed
  debug:
    var: flatpak_remove
- name: Uninstall packages
  ansible.builtin.package:
    name: "{{ flatpak_remove }}"
    state: absent
  when: flatpak_remove
