---
- name: prepare install variables
  include_tasks: "1prepare_install.yml"
- name: prepare install variables
  include_tasks: "2prepare_remove.yml"
- name: Remove tasks
  include_tasks: "4remove.yml"
- name: Install tasks
  include_tasks: "5install.yml"

