---
galaxy_info:
  role_name: ansible_packages
  author: Jochen Demmer
  description: Removes or installs packages, either on a scale of host, group or role.
  company: libcom.de
  issue_tracker_url: https://github.com/imp1sh/ansible_managemynetwork/issues
  license: BSD-3-Clause
  min_ansible_version: "2.9"
  platforms:
    - name: Alpine
      versions:
      - all
    - name: Debian
      versions:
        - all
    - name: EL
      version:
      - 5
      - 6
      - 7
      - 8
    - name: FreeBSD
      versions:
      - all
    - name: OpenWrt
      version:
      - all
  galaxy_tags: [packages, dpkg, apt, dnf, yum, pkgng, apk]
dependencies: []
