- name: FreeBSD Install /etc/resolv.conf
  template:
          src: resolv.conf.j2
          dest: /etc/resolv.conf
          owner: root
          group: wheel
          mode: 0644
  when: systemdns_dnsservers is defined
